In [29]:
import numpy as np

In [30]:
a = np.random.randn(5)
a

# these are not (1,5) matrices there are rank 1 array

array([ 0.64436074,  1.65855455, -0.63635278, -1.76833207,  1.50665827])

In [31]:
a.shape

(5,)

In [32]:
a.T

array([ 0.64436074,  1.65855455, -0.63635278, -1.76833207,  1.50665827])

In [33]:
(a.T).shape

(5,)

In [34]:
c = np.dot(a,a.T)
c

np.float64(8.967966253442263)

In [35]:
c.shape

# weird output

()

## allways prefer this method

In [36]:
b = np.random.randn(5,1)
b # (5,1)

array([[ 1.3279513 ],
       [ 1.31089168],
       [-0.6301166 ],
       [-1.22978869],
       [-0.5409733 ]])

In [37]:
b.T # (1,5)

array([[ 1.3279513 ,  1.31089168, -0.6301166 , -1.22978869, -0.5409733 ]])

In [38]:
np.dot(b,b.T) # (5,5)

array([[ 1.76345466,  1.74080032, -0.83676415, -1.63309949, -0.71838619],
       [ 1.74080032,  1.718437  , -0.8260146 , -1.61211976, -0.70915739],
       [-0.83676415, -0.8260146 ,  0.39704692,  0.77491026,  0.34087625],
       [-1.63309949, -1.61211976,  0.77491026,  1.51238022,  0.66528284],
       [-0.71838619, -0.70915739,  0.34087625,  0.66528284,  0.29265211]])

## broadcasting

In [39]:
A = np.array([
#   Apple  Orange Guava   Cherry
    [56.0, 0.0,    4.4,   68.0], # carbs
    [1.2, 104.0,   52.0,   8.0], # protein
    [1.8, 135.0,   99.0,   0.9]  # Fat
])
A

array([[ 56. ,   0. ,   4.4,  68. ],
       [  1.2, 104. ,  52. ,   8. ],
       [  1.8, 135. ,  99. ,   0.9]])

In [40]:
cal = A.sum(axis=0) # column-wise
cal

array([ 59. , 239. , 155.4,  76.9])

In [41]:
cal = cal.reshape(4,1)
cal.shape

(4, 1)

In [42]:
cal

array([[ 59. ],
       [239. ],
       [155.4],
       [ 76.9]])

In [43]:
A.shape

(3, 4)

In [44]:
# calculate the percentage of carbs, protein and fat in each fruit-type column-wise
percentage = 100*A.T/cal
percentage

array([[94.91525424,  2.03389831,  3.05084746],
       [ 0.        , 43.51464435, 56.48535565],
       [ 2.83140283, 33.46203346, 63.70656371],
       [88.42652796, 10.40312094,  1.17035111]])

In [45]:
percentage = 100*A/cal.reshape(1,4)
percentage

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])