### Numpy

we use numpy because list in python are very slow and can take multiple datatypes
whereas numpy is highly optimized c++ library which performs fast operations over array() and takes 
similar datas as input

Still we can keep different datatypes in numpy array but we generally dont do

In [3]:
import numpy as np
import time
import os

In [2]:
lists = [1,2,3,4,5]
print("List multiplication: ",lists*2) # duplicate created

array = np.array(lists)
print("array multiplication: ",array*array) # element wise multiplication

List multiplication:  [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
array multiplication:  [ 1  4  9 16 25]


In [4]:
arr_id = np.array([1,2,3,4,5,6]) # array in numpy takes list from python as input []
print("\n\n1D array: ",arr_id)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D array:\n",arr_2d)



1D array:  [1 2 3 4 5 6]
2D array:
 [[1 2 3]
 [4 5 6]]


### Time calculation

In [6]:
start1 = time.time()

new_list = [i*2 for i in range(10002200)]
print("Time taken for list calc: ",time.time()-start1)

start2 = time.time()
numpy_array = np.arange(10002200)*2
print("Time taken for array calc: ",time.time()-start2)

Time taken for list calc:  0.24221062660217285
Time taken for array calc:  0.018186330795288086


### zeros, ones, full, random.random, arange

In [ ]:
zeros1 = np.zeros(10,int)
zeros2 = np.zeros((3,4),int)
print("zero array:\n ",zeros1)
print("zero array:\n ",zeros2)


ones1 = np.ones(10,int)
ones2 = np.ones((3,4),int)
print("ones array:\n ",ones1)
print("ones array:\n ",ones2)

full = np.full((3,4),7,int)
print("full array:\n ",full)


random = np.random.random((4,5))
print("Radom array:\n ",random)

sequence = np.arange(1,20,2)
print("sequence array:\n ",sequence)

zero array:
  [0 0 0 0 0 0 0 0 0 0]
zero array:
  [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
ones array:
  [1 1 1 1 1 1 1 1 1 1]
ones array:
  [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
full array:
  [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
Radom array:
  [[0.36972491 0.59810796 0.72729681 0.38484178 0.02839927]
 [0.00383497 0.42783389 0.7553764  0.97640587 0.71583143]
 [0.3077067  0.00634488 0.84441874 0.29468222 0.9485344 ]
 [0.81287011 0.79290597 0.89115283 0.94958523 0.27609725]]
sequence array:
  [ 1  3  5  7  9 11 13 15 17 19]


### vector, matrix, tensor

In [8]:
vector = np.array([1,2,3,4,5]) # 1D == vector
print("vector: \n",vector)

matrix = np.array([[1,2,3,4],
                   [5,6,7,8],
                  [33,5,7,10]])   # 2D == matrix
print("matrix: \n",matrix)



Tensor = np.array([[[1,2,3],[4,5,6]], # >=3D == tensor
                    [[4,3,7],[1,7,8]],
                    [[3,5,4],[8,7,6]]])
print("Tensor: \n",Tensor)

vector: 
 [1 2 3 4 5]
matrix: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [33  5  7 10]]
Tensor: 
 [[[1 2 3]
  [4 5 6]]

 [[4 3 7]
  [1 7 8]]

 [[3 5 4]
  [8 7 6]]]


### Array properties

In [9]:
arr = np.array([[1,2,3],
                [4,5,6],
                [44,6,5]]) 
# they dont allow inhomogeneous shape, i.e allways has to be square or rectangle matrix

print("shape: ",arr.shape)
print("dimention: ",arr.ndim)
print("size: ",arr.size) # no of elements present
print("data type: ",arr.dtype)

shape:  (3, 3)
dimention:  2
size:  9
data type:  int64


### Array reshaping

In [10]:
#Array reshaping

arr = np.arange(16)
print("original array: \n",arr)

# need to be exactly no of elements = rows*col otherwise throws error
reshaped = arr.reshape((4,4)) 
print("reshaped array: \n",reshaped)

flattened = reshaped.flatten()
print("flattened array: \n",flattened)

raveled = reshaped.ravel()
print("raveled array: \n",raveled)

original array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
reshaped array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
flattened array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
raveled array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


### Transpose of a matrix

In [11]:
#Transpose of a matrix     rows <==> cols

Transpose = reshaped.T
print("Transposed matrix: \n",Transpose)

Transposed matrix: 
 [[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]


### Slicing

In [12]:
arr_1d = np.arange(11)
print("Original array:\n",arr_1d)

# slicing in 1D array
print("sliced array:\n",arr_1d[3:8])
# with step
print("sliced array:\n",arr_1d[3:8:2]) 
# backwards
print("sliced array:\n",arr_1d[8:2:-1]) 


# slicing in 2D array
arr_2d = np.array([
                    [1,2,3],
                    [4,5,6],
                    [7,8,9]]) 
print("original matrix:\n",arr_2d)
print("specific element:\n",arr_2d[1,1]) # [row,col]
print("Entire row:\n",arr_2d[2]) # row_indx
print("column:\n",arr_2d[:, 1:3]) # all rows of of 1st to 2nd column
# [:, start:stop]   start,stop for columns (stop is excluded)

Original array:
 [ 0  1  2  3  4  5  6  7  8  9 10]
sliced array:
 [3 4 5 6 7]
sliced array:
 [3 5 7]
sliced array:
 [8 7 6 5 4 3]
original matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
specific element:
 5
Entire row:
 [7 8 9]
column:
 [[2 3]
 [5 6]
 [8 9]]


### Sorting

In [14]:
unsorted = np.array([2,66,8,3,0,12])
print("original array: ",unsorted)
print("Sorted array: ",np.sort(unsorted))

array_2d = np.array([[13,12,3],[8,2,3],[5,5,98],[2,7,7]])
print("original 2D array:\n ",array_2d)
print("Sorted 2D array by column:\n",np.sort(array_2d,axis=0)) # column-wise(top-bottom)
print("Sorted 2D array by row:\n",np.sort(array_2d,axis=1)) # row-wise(left-right)

original array:  [ 2 66  8  3  0 12]
Sorted array:  [ 0  2  3  8 12 66]
original 2D array:
  [[13 12  3]
 [ 8  2  3]
 [ 5  5 98]
 [ 2  7  7]]
Sorted 2D array by column:
 [[ 2  2  3]
 [ 5  5  3]
 [ 8  7  7]
 [13 12 98]]
Sorted 2D array by row:
 [[ 3 12 13]
 [ 2  3  8]
 [ 5  5 98]
 [ 2  7  7]]


### Mask, Where

In [15]:
#Filter with mask
# numbers = numpy.array([i for i in range(1,11)])   <--- slow
numbers = np.arange(1,11)
mask = numbers%2 == 0
print("type of mask: ",type(mask))
print("mask = ",mask)

even_numbers = numbers[mask]
print("Even numbers using mask: ",even_numbers,end="\n\n")

# where()
where_indx = np.where(numbers > 7)
print("type of where: ",type(where_indx))
print("where = ",where_indx)
print("numbers greater than 7 using where: ",numbers[where_indx],end="\n\n")

# transforms the whole array and doesnot return indices in the form of tupil
new_condition = np.where(numbers > 5, numbers*2, numbers)
print("new where condition array: ",new_condition)

type of mask:  <class 'numpy.ndarray'>
mask =  [False  True False  True False  True False  True False  True]
Even numbers using mask:  [ 2  4  6  8 10]

type of where:  <class 'tuple'>
where =  (array([7, 8, 9]),)
numbers greater than 7 using where:  [ 8  9 10]

new where condition array:  [ 1  2  3  4  5 12 14 16 18 20]


In [16]:
#Adding and removing data

array1 = np.array([1,2,3,8])
array2 = np.array([4,5,6,7])

# it will not concatenate it will be just added and shape of array needs to be same
combined = array1 + array2
print("added array: ",combined)

concat = np.concatenate((array1,array2)) # takes tupil as input
print("concatenated array: ",concat)

# array compatibility

a = np.array([1,2,3])
b = np.array([5,6,7])
print("compatibility shape",a.shape == b.shape)

added array:  [ 5  7  9 15]
concatenated array:  [1 2 3 8 4 5 6 7]
compatibility shape True


### Adding , Deleting row and col

In [ ]:
original = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("original:\n", original)

# Add row
with_new_row = np.vstack((original,[55,44,33]))
print("after adding new row:\n", with_new_row)

# Correct 3×1 column
new_col = np.array([[55],
                    [44],
                    [33]])

# Add column
with_new_col = np.hstack((original, new_col))
print("after adding new col:\n", with_new_col)


#deletion using delete() returns array after delete
deleted_array_row = np.delete(original,1,axis=0) #removes first indexed row
deleted_array_col = np.delete(original,1,axis=1) #removes first indexed col
print('\nafter row delete:\n',deleted_array_row)
print('\nafter col delete:\n',deleted_array_col)

original:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
after adding new row:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [55 44 33]]
after adding new col:
 [[ 1  2  3 55]
 [ 4  5  6 44]
 [ 7  8  9 33]]

after row delete:
 [[1 2 3]
 [7 8 9]]

after col delete:
 [[1 3]
 [4 6]
 [7 9]]
